### PR TITLE
Update triggers object to use v1beta1

### PR DESCRIPTION
**Pull request by savitaashture**
Fixes: https://issues.redhat.com/browse/SRVKP-1627

/cc @praveen4g0 @VeereshAradhya @khrm

### CODE REVIEW

**Comment by savitaashture** [comment]
@ppitonak @VeereshAradhya friendly reminder on testing this change :smile_cat:

**Comment by ppitonak** [comment]
@savitaashture we are waiting for some nighly build to test with ;)

**Review by piyush-garg — APPROVED** [review]

**Review by ppitonak — APPROVED** [review]
Verified with 1.6 (build 131233)

**Comment by vdemeester** [comment]
@savitaashture @ppitonak we need to have this cherry-picked to the 1.6 branch right ?

**Comment by ppitonak** [comment]
@vdemeester yes

**Pull request merged**
