### PR TITLE
Update Tutorial for Openshift 4.2 and Pipelines 0.7.0

### PR DESCRIPTION
**Pull request by danielhelfand**
This pull request updates screenshots and directions of navigating the web console for OpenShift 4.2, including installation instructions. 

It also updates the YAML for the pipeline in the README to match ARG updates needed for 0.7.0 if a user wants to create a pipeline through the web console.

Also corrects typos and edits some writing.

#6 is still a big problem if using a cluster with `LimitRange` settings, and it might be worthwhile pointing this out somewhere in the README in a future pr. The workarounds in the issue should work to make sure the pipeline succeeds.

### CODE REVIEW

**Review by siamaksade — APPROVED** [review]

**Comment by chmouel** [comment]
/lgtm
/approve
/meow

Thanks 🙇🏽‍♂️😻

**Pull request merged**
