### PR TITLE
Updating the pipeline-1.14 branch readme links

### PR DESCRIPTION
**Pull request by sudhishmk**
Updated all links for branch pipelines-1.14 with links from pipelines-1.14 instead of master branch.

### CODE REVIEW

**Review by savitaashture — APPROVED** [review]
/lgtm

**Review by khrm — COMMENTED** [review]
/approve

**Comment by savitaashture** [comment]
@sudhishmk you need to update the links for frontend to -> https://github.com/openshift/pipelines-vote-ui/tree/pipelines-1.4 and backend to -> https://github.com/openshift/pipelines-vote-api/tree/pipelines-1.14 in the readme

**Review by khrm — COMMENTED** [review]
We also need to change pipeline and TriggerTemplate.

**Comment by khrm** [comment]
Like here: https://github.com/openshift/pipelines-tutorial/commit/04be42b0c59a9d85451a54a4cba12212371e7011

**Comment by sudhishmk** [comment]
> @sudhishmk you need to update the links for frontend to -> https://github.com/openshift/pipelines-vote-ui/tree/pipelines-1.4 and backend to -> https://github.com/openshift/pipelines-vote-api/tree/pipelines-1.14 in the readme

updated

**Comment by sudhishmk** [comment]
> We also need to change pipeline and TriggerTemplate.

Done

**Comment by khrm** [comment]
@sudhishmk Change here also: https://github.com/openshift/pipelines-tutorial/pull/175/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L336

**Comment by sudhishmk** [comment]
> @sudhishmk Change here also: https://github.com/openshift/pipelines-tutorial/pull/175/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L336

Done

**Pull request merged**
