### PR TITLE
Editing Pipelines Tutorial Documentation

### PR DESCRIPTION
**Pull request by danielhelfand**
This pull request addresses issues with grammar and typos found while going through the `pipelines-tutorial`.

### CODE REVIEW

**Comment by danielhelfand** [comment]
@siamaksade @vdemeester @sthaha Can any of you take a look at this when you have a moment?

**Review by siamaksade — APPROVED** [review]

**Comment by siamaksade** [comment]
@danielhelfand thanks for the PR :)

**Comment by danielhelfand** [comment]
@siamaksade Sure thing! Thanks for the review.

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
