### PR TITLE
Add patch to tkn command to use default params

### PR DESCRIPTION
**Pull request by pthangad**
* Now tkn promts for default value if it's not specified at runtime while running `tkn start pipeline/task` command
Please do refer [issue](https://github.com/tektoncd/cli/issues/1180)

updated demo script and README.md file

### CODE REVIEW

**Comment by pthangad** [comment]
cc: @VeereshAradhya @piyush-garg @pradeepitm12 @ppitonak

**Review by VeereshAradhya — APPROVED** [review]
/lgtm

**Comment by sounix000** [comment]
Just for the record: Doc PR https://github.com/openshift/openshift-docs/pull/34897

**Pull request merged**
