### PR TITLE
Update tutorial for pipelines 1.17

### PR DESCRIPTION
**Pull request by zakisk**
updated tutorial for pipelines 1.17

Signed-off-by: Zaki Shaikh <zashaikh@redhat.com>

### CODE REVIEW

**Comment by rupalibehera** [comment]
I guess this PR should be raised for `pipelines-1.17` branch and not `master` cc: @savitaashture

**Comment by zakisk** [comment]
@rupalibehera changed base to 1.17

**Comment by savitaashture** [comment]
> I guess this PR should be raised for `pipelines-1.17` branch and not `master` cc: @savitaashture

yes it should be on  `pipelines-1.17`

**Comment by savitaashture** [comment]
/lgtm

Thank you

**Review by savitaashture — APPROVED** [review]

**Pull request merged**
