### PR TITLE
Update branch info for vote-api and vote-ui

### PR DESCRIPTION
**Pull request by savitaashture**
/cc @praveen4g0 @vdemeester

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/cc @praveen4g0

**Review by pthangad — COMMENTED** [review]
Seems I cannot comment :wink:

**Comment by pthangad** [comment]
looks good :heart: 
Verified against 1.3.0  :heavy_check_mark: 
/lgtm

**Comment by chmouel** [comment]
Something weird on PSI
```
153m        Warning   FailedScheduling   pod/pipeline-tutorial-check-pr-fetch-49nvd-pod-28d2n   error while running "VolumeBinding" prebind plugin for pod "pipeline-tutorial-check-pr-fetch-49nvd-pod-28d2n": Failed to bind volumes: timed out waiting for the condition
143m        Warning   FailedScheduling   pod/pipeline-tutorial-check-pr-fetch-49nvd-pod-28d2n   error while running "VolumeBinding" prebind plugin for pod "pipeline-tutorial-check-pr-fetch-49nvd-pod-28d2n": Failed to bind volumes: timed out waiting for the condition
123m        Warning   FailedScheduling   pod/pipeline-tutorial-check-pr-fetch-49nvd-pod-28d2n   error while running "VolumeBinding" prebind plugin for pod "pipeline-tutorial-check-pr-fetch-49nvd-pod-28d2n": Failed to bind volumes: timed out waiting for the condition
112m        Warning   FailedScheduling   pod/pipeline-tutorial-check-pr-fetch-49nvd-pod-28d2n   error while running "VolumeBinding" prebind plugin for pod "pipeline-tutorial-check-pr-fetch-49nvd-pod-28d2n": Failed to bind volumes: timed out waiting for the condition
103m        Warning   FailedScheduling   pod/pipeline-tutorial-check-pr-fetch-49nvd-pod-28d2n   skip schedule deleting pod: pull-129-d3fab-oq/pipeline-tutorial-check-pr-fetch-49nvd-pod-28d2n
103m        Warning   FailedScheduling   pod/pipeline-tutorial-check-pr-fetch-49nvd-pod-28d2n   error while running "VolumeBinding" prebind plugin for pod "pipeline-tutorial-check-pr-fetch-49nvd-pod-28d2n": Failed to bind volumes: pod "pull-129-d3fab-oq/pipeline-tutorial-check-pr-fetch-49nvd-pod-28d2n" does not exist any more
163m        N
```

**Review by khrm — APPROVED** [review]
/lgtm

**Comment by chmouel** [comment]
/lgtm

Looking Good! 🤙🏽

**Pull request merged**
