### PR TITLE
Fix update-deployment task that does not need a workspace(readme.md)

### PR DESCRIPTION
**Pull request by pthangad**
Issue [#122](https://github.com/openshift/pipelines-tutorial/issues/122)
Here is fix to `README.md` file

### CODE REVIEW

**Review by savitaashture — APPROVED** [review]
/lgtm

**Comment by savitaashture** [comment]
cc @chmouel

**Comment by chmouel** [comment]
/lgtm
Looks good to me, thanks! 👍

**Comment by chmouel** [comment]
/lgtm
/approve
🚀

**Pull request merged**
